home:
  name: TellTheWorld
  logo: https://legalpage.org/images/logo.png # 264px * 80px
  description: Legal stuff from Tell The World
  website: "https://telltheworld.today"
  hideFooter: false # Please don't ❤

pages:
- name: Privacy
  file: privacy.md

- name: Terms
  file: terms.md

- name: Cookies
  file: cookies.md

- name: Imprint
  file: imprint.md

placeholder:
 SERVICE: https://telltheworld.today
 EMAIL: hello@telltheworld.today
 COMPANY: Tell the World GmbH
